name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js with Volta
        uses: volta-cli/action@v1

      - name: Install dependencies
        run: npm install

      - name: Check formatting with Prettier
        run: npm run format:check

      - name: Lint with ESLint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Check types with TypeScript + JSDoc
        run: npm run typecheck
